spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eorganization_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true

jwt:
  secret: b1de5932e095776289bc0dd3530c72ea88b7ce2aedf3d1913878b2ae9a978d88
  accessTokenValiditySeconds: 600     # 10 minutes
  refreshTokenValiditySeconds: 1209600 # 14 days

server:
  port: 8081
